### ISSUE TITLE
Wrong CanId

### ISSUE THREAD

**Issue by BIERAAP** [Seeed-Studio/CAN_BUS_Shield#31]
For some reason im receiving the wrong / incorrect CanID's.

ID: 18	should be 418
ID: 8	should be 408
ID: 10	schould be 410
ID: A0	schould be 4A0

Any idea what i did wrong or whats happening

**Comment by BlueAndi** [comment]
Sounds like you assigned it to a 8-bit variable, therefore the everything above 0xff is cut.

**Comment by BIERAAP** [comment]
im using the example code (receive_check.ino)  included in the project.

**Comment by BlueAndi** [comment]
And there is a bug

` unsigned char canId = CAN.getCanId();`

;-)

**Comment by BIERAAP** [comment]
omg i feel so stupid... Think its time for holiday!! haha big thanks BlueAndi

**Comment by loovee** [comment]
Thanks guys. will fix the bug now.
