### ISSUE TITLE
GMLAN Baudrates

### ISSUE THREAD

**Issue by szechyjs** [Seeed-Studio/CAN_BUS_Shield#4]
To accommodate use on GMLAN the following baud rates need added

```
33.33KBPS
95.2KBPS
```

**Comment by KotieSmit** [comment]
> On another note, it looks like every arduino CAN library uses different values for these config registers. Once my Saleae Logic 8 ships I plan on sitting down with all the various libraries and checking their bit timing configurations.

I know this is very old.  Did you manage to check the different libraries' timings?
