### ISSUE TITLE
Board Compatibility

### ISSUE THREAD

**Issue by jsdevel** [Seeed-Studio/CAN_BUS_Shield#54]
Hi,

I mistakenly bought an elecfreak/makerfocus v1.2 version of the shield.  https://www.amazon.com/gp/product/B06XWQ4WF9/ref=oh_aui_detailpage_o02_s02?ie=UTF8&psc=1

Will this project work with it?

**Comment by loovee** [comment]
Yes, only the logo is different. 
Thanks.

**Comment by jsdevel** [comment]
Thanks for the reply!
