### ISSUE TITLE
How to edit the value of CRC field in a data frame?

### ISSUE THREAD

**Issue by alyahya** [Seeed-Studio/CAN_BUS_Shield#69]
Hello,

I would like to have access and to change the value of CRC sequence of a data frame before sending. Can someone please tell me where in the code is the CRC being generated (the sender), and where it is being read to verify a received frame?

Regards.

**Comment by Jenkinlu001** [comment]
CRC verification in CAN communication process is generated by hardware and does not need to be implemented by software.

**Comment by alyahya** [comment]
I know. For my research, I wanted to implement a different type of CRC that supports authentication as well.
