### ISSUE TITLE
Cannot send messages longer than LEN=8

### ISSUE THREAD

**Issue by mnd31** [Seeed-Studio/CAN_BUS_Shield#87]
Creating a message with CAN.sendMsgBuf with LEN set larger than 8 does not result in the full message being sent to the bus. 9-13 cuts the data off at 8 bytes. Anything longer than 14 causes very strange behavior.

**Comment by Teddyz** [comment]
I think a CAN message can only be from 0 to 8 bytes long, unless using CAN FD which I think this chip does not support.
If you want longer messages to be sent you have to invent or use a protocol to split them into many frames.  See https://en.wikipedia.org/wiki/ISO_15765-2

**Comment by mnd31** [comment]
Yep, you're correct. Looks like I need to find an MCP2517FD implementation instead. Thanks.
